# Generated by Django 6.1 on 2026-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_revelacao', models.DateTimeField()),
            ],
        ),
    ]
