# Generated by Django 6.1 on 2026-08-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsula',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='capsulas/'),
        ),
    ]
