# Generated by Django 6.1 on 2026-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulas', '0003_capsula_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsula',
            name='conteudo',
        ),
        migrations.AlterField(
            model_name='capsula',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capsula',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
