# Generated by Django 6.1 on 2026-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulas', '0004_remove_capsula_conteudo_alter_capsula_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsula',
            name='conteudo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
